### ISSUE TITLE
Support for army builder summary format 

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#100]
As can be seen in this thread 
https://www.the-ninth-age.com/community/index.php?thread/61724-poland-lodz-master-17-07-18-07-teams-3x4500/&postID=1716544#post1716544

there is another common format for lists could we please also accept this with the formater

**Comment by marcqg** [comment]
I think that the same as #94

**Comment by duxbuse** [comment]
Yeeha perfect its the `name @ 95pts` format so I agree I think this is a duplicate.
