### ISSUE TITLE
List_as_string without playername

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#109]
Id like to use to List_as_string field in the dashboard. In many case the playername is in that field too. Can it be deleted so we don't publish the name in the dashboard?

**Comment by duxbuse** [comment]
I kinda want that field for more debugging purposes which requires all the data as is. Is it easy for you to simply ignore the first line of the field?

**Comment by SanderND** [comment]
i think so. First line must be always the playername then. Is that so?

**Comment by duxbuse** [comment]
Yes

**Comment by SanderND** [comment]
I will start fixing this in Tableau by splitting the field by a formula and then keeping the field out of the publication of the dashboard to Tableau's public server

**Comment by SanderND** [comment]
After some tries in Tableau I simply think that solving this either in the formatter or backend is better. Sometimes the field comes with playername, sometimes without. So I have to unassign myself on this one.
