### ISSUE TITLE
casual games are handled in KPI and external performace page too.

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#118]
Casual games have no ranking on a tourney. Our combined metric is:

([Results (avg) per game per army (normalized)])*([Z_weighting_ranking]/100)
+
avg([z_list_placing_average_per_army])*((100-([Z_weighting_ranking]))/100)

As the 2nd part of the formula will return zero for casual games, the metric isnt correct. Therefore this formula should always do 100% * [Results (avg) per game per army (normalized)] in case the event type = casual.

**Comment by SanderND** [comment]
Formula as i think it should be:

IF([event_type]='CASUAL') THEN
([Results (avg) per game per army (normalized)])
ELSE ([Results (avg) per game per army (normalized)])*([Z_weighting_ranking]/100)
+
avg([z_list_placing_average_per_army])*((100-([Z_weighting_ranking]))/100)
END


Error i get is the infamous cannot mix aggregrated and non aggregrated results in IF expression.

**Comment by duxbuse** [comment]
Is this sql or tableau specific code?

**Comment by SanderND** [comment]
It ia tableau specific. But heavily based on SQL.

Please note the formula is using other calculated fields. I will post their code so you can better understand what im doing.

**Comment by SanderND** [comment]
fixed! for CASUAL events now only the average is taken into account disregardless of the selection of the parameter setting by the user. This is good as casual games have only an average per game.
