### ISSUE TITLE
Blending datasources create too many front end limitations

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#123]
Blending two datasources in Tableau limits the development possibilities too much. Data should come pre-joined from GCS. 

Join: static unit data to lists based on the name of the unit and name of the army.

**Comment by SanderND** [comment]
Working on this. Steps to take on GCS:

1) selfjoin to find opponents armyname in the TBL_TABLEAU_INTERFACE query
2) replace exclude join by a regular join which explicitly selects the fields i want in the TBL_TABLEAU_INTERFACE query
3) join the static data for only those columns i need in the TBL_TABLEAU_INTERFACE query
4) test in Tableau
5) remove obsolete queries and put only one interface query in 'views' package.

**Comment by duxbuse** [comment]
@SanderND I think you managed this, is the ticket still required?

**Comment by SanderND** [comment]
Yes, im working on this. But its not finished. I need the correct version in the list data to properly join to the static data. When that is done i can try to close this issue.

**Comment by SanderND** [comment]
Done!
