### ISSUE TITLE
Units that exist in multiple categories correctly allocated

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#144]
The static data has the OrgName of a unit. e.g. A unit of Marksmen is Core for Dwarven Holds. However, in some armies a unit exists in more than one category. As a result Tableau cannot choose which OrgName belongs to the unit. This creates issues for the Internal Balance tab, as some units do not get allocated.

Ideally, the parses decided itself which OrgName belongs to it and stores this data.

**Comment by SanderND** [comment]
Solved in Tableau by linking both armyname and unitname. This resolved entries like 'warriors' which exist in multiple armies.

Sometimes mounts (e.g. skysloop) exist in multiple categories too. But as character mounts are in our field unit upgrade we can assume all mounts that are entered as unit are thus to be categorized to the other unit category. E.g. naval ordnance in case of the skysloop. unitnames that are not home in any of the other categories are bad entries and get army category = null and are catched by the quality monitoring.

**Comment by duxbuse** [comment]
Is this resolved then?

**Comment by SanderND** [comment]
No this is not solved. My Tableau solution only fixed mounts which were chose as monster entry (e.g. Gargantula). However, a unit like warhounds (WDG) can be core or special. My Tableau solution didnt fix that. Issue #147 is about the same thing so can be merged i think.

**Comment by SanderND** [comment]
Solved with new query for interface to Tableau.
