### ISSUE TITLE
Extra armyname in static data

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#145]
The static data on units has different armynames as in the NewRecruit format.

Names in NewRecruit format:
Åsklanders
Beast Herds
Cultists
Daemon Legions
Dread Elves
Dwarven Holds
Empire of Sonnstahl
Highborn Elves
Hobgoblins
Infernal Dwarves
Kingdom of Equitaine
Makhar
Ogre Khans
Orcs and Goblins
Saurian Ancients
Sylvan Elves
Undying Dynasties
Vampire Covenant
Vermin Swarm
Warriors of the Dark Gods

Armynames in static data:
ArmyName
Warriors of the Dark Gods (v2022 beta 2)
Vermin Swarm (v2022 alpha 3)
Vampire Covenant (v2022 beta 2)
Undying Dynasties (v2022 beta 2)
Sylvan Elves (v2022 beta 2)
Saurian Ancients (v2022 beta 2)
Orcs and Goblins (v2022 beta 2)
Ogre Khans (v2022 beta 2)
Nippon (v 2.3.1)
Makhar (v2021 2 edition)
Kingdom of Equitaine (v2022 alpha 2)
Infernal Dwarves (v2022 beta 1 hotfix 2)
Hobgoblins(v2021 beta 1 hotfix 1)
Highborn Elves (v2022 beta 2)
Empire of Sonnstahl (v2022 beta 2)
Dwarven Holds (v2022 beta 2)
Dread Elves (v2022 beta 1 hotfix 1)
Daemon Legions (v2022 beta 2)
Cultists (v2021 beta 2)
Beast Herds (v2022 beta 2)
ÅSKLANDERS (v2021 2 edition)

As you see the names in the static data has some extra version info in the name. This info is stored separately too. The issue of different names makes it hard to join the fields for referencing armyinformation to units. Therefore please align the armynames exactly.

Meanwhile I create a calculated field in Tableau to temporarily work around this issue.

**Comment by marcqg** [comment]
Done :)

**Comment by SanderND** [comment]
@duxbuse : i opened this ticket for the addition. As @zikum now has this info in the formatter. Can you put that data into the lists_data table?
