### ISSUE TITLE
Formatter returning wrong expected points

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#148]
Got a report on 20/08/2022

Included the following unit

```375 - 10 Sylvan Sentinels, Sylvan Blades, Scout```

As per the book this is the right cost but formatter returned expecting `339`

https://discord.com/channels/910334907736272906/915385291429269505/1010187984575926272

**Comment by duxbuse** [comment]
So the root of this was the `DEAD` prefix that warhall can provide.

Warhall can also send `HALF` as an option so I think we need to handle that as well

**Comment by marcqg** [comment]
The formater can now process DEAD and HALF :)

**Comment by duxbuse** [comment]
Looks to be working fine now
