### ISSUE TITLE
FORMATTER: GREED

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#149]
Under WTDG

Units can take the mark of greed, this then enables many weapons that are not recognised.

EG.
https://discord.com/channels/910334907736272906/915385291429269505/1010189410198884412

`Unit: Chosen Knights, Could not find option Paired Weapons`
`Unit: Chosen Knights, Could not find option Great Weapon`

**Comment by marcqg** [comment]
It's fixed :)
