### ISSUE TITLE
FORMATTER: PRICE WRONG

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#151]
`DEAD 505 - 10 Taurukh Enforcers, Infernal Weapon, Shield, Blunderbuss, Champion, Musician, Standard Bearer (Stalker's Standard)`

This is correct price
https://discord.com/channels/910334907736272906/915385291429269505/1010523195079671829

Formatter thinks is should be 
```text
Player1
Army: Use version 2 Nd Edition, Version 2022
Unit: Taurukh Enforcers, invalid cost: 505, correct cost: 525
```

**Comment by marcqg** [comment]
it's fixed :)
