### ISSUE TITLE
FORMATTER: Swarm priest

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#153]
` 275 - Swarm Priest, Wizard Adept, Thaumaturgy, Binding Scroll, Holy Triumvirate, Caelysian Pantheon`
`420 - Swarm Priest, Sacred Platform (Whispering Bell), Wizard Apprentice, Witchcraft, Rod of Battle, Holy Triumvirate, Caelysian Pantheon`
` 606 - 47 Blackfur Veterans, Champion, Musician, Standard Bearer with Eagle Standard (Rending Banner)`

https://discord.com/channels/910334907736272906/915385291429269505/1010523090083659906

```text
Army: Use version 2 Nd Edition, Version 2022 Beta 1
Unit: Swarm Priest, invalid cost: 420, correct cost: 430
Unit: Swarm Priest, invalid cost: 275, correct cost: 285
Unit: Blackfur Veterans, invalid cost: 606, correct cost: 591
```

**Comment by marcqg** [comment]
it's fixed :)
