### ISSUE TITLE
win rates per map and objective

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#180]
Would love to see a chart plotting win rates on a per map and objective to see if there are any outliers that should be further investigated.

**Comment by SanderND** [comment]
step 1: add map and objective fields to interface query in GCS
step 2: make first prototype dashboards

**Comment by SanderND** [comment]
step 1 done, also added 'first turn' and and 'deployment selected' for similar purposes

**Comment by SanderND** [comment]
Not enough results per map. First turn games are now analyzable on tab Game Setup Balance. Will close this ticket for now.
