### ISSUE TITLE
Split out discord names from actual names

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#20]
Convert something like this `Marius Maertens (masterchief90#8596)` into 2 separate fields.

**Comment by marcqg** [comment]
Do you want split  as : 
Marius Maertens
masterchief90#8596

or other format ?

**Comment by duxbuse** [comment]
Still not 100% sure on this. I really wanted to strip it so that we had consistency with player name such that you could filter on your own name and see your results.  We are currently starting to make an alias spreadsheet with multiple names for the same person  perhaps we add the discord name to the alias list or perhaps we save it as a seperate vale in the data base . Open to ideas

**Comment by marcqg** [comment]
split the line in two and try to match the first or the second line ?

**Comment by marcqg** [comment]
What format do you want ?

**Comment by duxbuse** [comment]
for privacy reasons I think that we are not going to go down this path.
