### ISSUE TITLE
GCS rights to delete queries and scheduled queries

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#200]
missing rights for Sander: 

**Remove scheduled queries:** 
Required permission(s): bigquery.transfers.update

Also, when i try to remove )obsolete) queries I created myself I get an error. I think it is permissions related as well:
![Schermafbeelding 2023-02-12 om 17 44 50](https://user-images.githubusercontent.com/96297411/218324531-f9ea3d5c-c957-45d2-94e5-42d272e09a0d.png)

**Comment by duxbuse** [comment]
You now have the Big query admin role. This is a scary role as it gives you god power in big query please be careful
