### ISSUE TITLE
Injest events from new recruits tournament features.

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#27]
examples:
https://www.newrecruit.eu/app/tournydetails?id=611ac82f2781604de4d20b8c

**Comment by marcqg** [comment]
Do you want to read list, result ?

**Comment by duxbuse** [comment]
Everything ideally we gather all of it.

**Comment by marcqg** [comment]
It's possible to do it, when a data is displayed on a web page, that can be read :)

**Comment by duxbuse** [comment]
Yeah but web scraping is quite brittle flammy has already said he is happy to expose this via api so was going to chase this up after Christmas. But with him being hacked might be a bit delayed . He also needed to do a bunch of work to handle old versions so this might be a long way off.

**Comment by marcqg** [comment]
Yes, no need to do web scraping, Flammy want to help us :)

**Comment by duxbuse** [comment]
Waiting on Flammy to update his api to present the army list in raw format, as the current format does not allow for us to correctly map unit upgrades to the specific instance of unit that took it.
