### ISSUE TITLE
Cache tourney keeper data

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#32]
Gather all tk data and load it into a big query table.

that allows the front end to use so metrics as well as makes the bot only need to perform db look ups rather than web requests should be more efficient.

**Comment by SanderND** [comment]
example metric we could make: % of played 9th age games covered. A statistical very relevant metric as it says something on the representativeness of our insights. When new sources of results come in, we can scale this metric and can try to chase goals with the entire project. E.g. 75% of tournament games covered.
