### ISSUE TITLE
List CR9 XV - Your bi-weekly dosis of UB Tournament give no feedback from the bot.

### ISSUE THREAD

**Issue by BaldinNL** [duxbuse/ninthage-data-analytics#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duxbuse** [comment]
Issue resolved

![image](https://user-images.githubusercontent.com/6869131/146858406-c0a34682-3fce-4bd8-94df-ab3f2e5c420f.png)
