### ISSUE TITLE
Multiplication of units

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#45]
**Describe the bug**
Units in list are read multiple times. 

**To Reproduce**
1. Upload this list into the bot:

Josh Stuart 
Dread Elves
445 - Warlock Outcast, Witchcraft, Ceinran's Gambit, Obsidian Rock
400 - Temple Legate, Battle Standard Bearer (Aether Icon, Aether Icon), Essence of Mithril, Blades of Darag, War Smith
310 - Legion Legate, General, Shield (Willow's Ward), Kraken's Hide, Alchemist's Alloy, Mask of the War Crow, Ring of the 9th Legion 
569 - 29 Temple Militants, Champion, Musician, Standard Bearer (Rending Banner)
307 - 18 Dread Legionnaires, Standard Bearer (Flaming Standard), Musician, Champion
250 - 15 Legion Auxiliaries, Champion, Musician
670 - 30 Judicators, Champion, Musician, Standard Bearer (Academy Banner)
600 - 25 Obsidian Guard, Champion, Musician, Standard Bearer (Eye of the Gorgon) 200 - Divine Altar, Effigy of Dread
160 - 8 Harpies
231 - 8 Black Cloaks
204 - 7 Black Cloaks
150 - 5 Black Cloaks 
4496

**Expected behavior**
It will give an error as the lists has more calculated points then stated in the last row. Root cause is that the process found 18 x a unit called 'Dread Legionnaires'.

**Additional context**
I see the duplication is the same as the number of models in the unit (18). There seems to be a correlation with the bug and that number.

**Comment by marcqg** [comment]
It's fixed :)
