### ISSUE TITLE
Multiplication of units (part 2)

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#46]
**Describe the bug**
Units get multiplied unwantedly. In this example: 90 - 2 Rat Swarms is converted as ('rat swarms', 90), ('rat swarms', 90)

**To Reproduce**
1) Add this list:

VS
870 - Vermin Daemon, General
350 - Chief, Monstrous Rat, Shield, Heavy Armour (Ghostly Guard), Great Weapon
315 - Chief, Vermin Hulk Bodyguard, Battle Standard Bearer (Banner of the Endless Swarm), Light Armour, Great Weapon, Sceptre of Vermin Valour
255 - Magister, Wizard Adept, Witchcraft, Binding Scroll
445 - 58 Rats - at - Arms, Spear, Standard Bearer (Banner of the Endless Swarm), Musician, Champion
395 - 50 Rats - at - Arms, Spear, Standard Bearer (Banner of the Relentless Company), Musician, Champion
150 - 20 Giant Rats
135 - 10 Footpads, Musician
715 - 11 Vermin Hulks, Champion
200 - 8 Plague Disciples
120 - 5 Gutter Blades, Throwing Weapons
90 - 2 Rat Swarms
230 - Lightning Cannon
230 - Lightning Cannon 
4500

**Expected behavior**
I expect 90 - 2 rat swarms to be read as a unit of 2 rat swarms for 90p.

**Comment by duxbuse** [comment]
hey @marcqg

is this still an issue?

**Comment by marcqg** [comment]
Yes, it's a problem of army version. 

Now rat swarms is not a unit as other but only a profil used by an other component of the army. 

I do not know hat to do for this case now

**Comment by duxbuse** [comment]
Can the formatter have a default case that if you cannot find the unit in the line as a legal unit entry that it just does the formatting and otherwise leaves it?

**Comment by marcqg** [comment]
I have modified the verification if the unit found is not anymore a selectable unit as Rat swarms now, no modification will be done on it

**Comment by duxbuse** [comment]
@SanderND can you confirm this is fine and close if its all good

**Comment by SanderND** [comment]
No unfortunately not. For example this list is not read correctly:

Cente
Warriors of the Dark Gods
655 - Barbarian Chief, General, Wasteland Behemoth, Trophy Rack, Paired Weapons, Hero’s Heart, Aether Icon, Obsidian Stone, Binding Scroll
820 - Exalted Herald
423 - 11x Warriors, C, Vanadra, Halberds
258 - 26x Barbarians, shields, C
119 - 2 x 8 Warhounds
325 - Battleshrine, Icon of Infinite
200 - Chimera
335 - 2 x 5 Warrior Knights, C, Great Weapon, Vanadra
455 - 2 x Feldrak Elder, Paired Weapons
4499


The last row, the feldraks went wrong.

**Comment by marcqg** [comment]
now, I have this : 

Cente
Warriors of the Dark Gods
655 - Barbarian Chief, General, Wasteland Behemoth, Trophy Rack, Paired Weapons, Hero's Heart, Aether Icon, Obsidian Stone, Binding Scroll
820 - Exalted Herald
423 - 11x Warriors, champion, Vanadra, Halberds
258 - 26x Barbarians, shields, champion
119 - 8x Warhounds
119 - 8x Warhounds
325 - Battleshrine, Icon of Infinite
200 - Chimera
335 - 5x Warrior Knights, champion, Great Weapon, Vanadra
335 - 5x Warrior Knights, champion, Great Weapon, Vanadra
455 - Feldrak Elder, Paired Weapons
455 - Feldrak Elder, Paired Weapons
4499

Feldrak Elder is 'single model', so duplicate the line is good no ?

**Comment by duxbuse** [comment]
@marcqg 

Just tried this into the formatter
```text
Cente
Warriors of the Dark Gods
655 - Barbarian Chief, General, Wasteland Behemoth, Trophy Rack, Paired Weapons, Hero’s Heart, Aether Icon, Obsidian Stone, Binding Scroll
820 - Exalted Herald
423 - 11x Warriors, C, Vanadra, Halberds
258 - 26x Barbarians, shields, C
119 - 2 x 8 Warhounds
325 - Battleshrine, Icon of Infinite
200 - Chimera
335 - 2 x 5 Warrior Knights, C, Great Weapon, Vanadra
455 - 2 x Feldrak Elder, Paired Weapons
4499
```
I get a 500 back.

This list is dodgy for 2 reasons though. `Vanadra` is not the proper upgrade it should be `wrath` and the `2 x unitname` format

**Comment by duxbuse** [comment]
Just re tested this and its working fine Big thanks to @marcqg
