### ISSUE TITLE
Document name change after uploading

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#47]
**Describe the bug**
Special characters are removed from the document name after uploading to bucket via the bot.

**To Reproduce**
1. Go to the discord bot.
2. Upload a file with name 'New Year's Revolution'
3. Conclude it is uploaded as 'New Years Revolution' instead

**Expected behavior**
It should stay the same new to allow correct matching with TK which need 100% matching name, including special characters.

**Comment by duxbuse** [comment]
This is a limitation with discord
https://support.discord.com/hc/en-us/community/posts/360037586071-Do-not-rename-files
Not much I can do.

## WORKARROUND
For files with names with grammar they will need to be manually uploaded to the bucket.
