### ISSUE TITLE
No authorization to change name of files in bucket

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#48]
**Describe the bug**
I have no authorization to change the name of word file uploaded into the bucket.

**To Reproduce**
1. Go to the bucket.
2. Browse to a file, try to rename via 'rename' option after clicking the three dots on the right of the file.
3. I get an 'access denied' error.

**Expected behavior**
I expected to rename the file.

**Comment by duxbuse** [comment]
Hey does the error say what permissions you need?

**Comment by SanderND** [comment]
The renaming command itself doesnt show a clear error. When I browse other aspects of the bucket I get : 

"There was an error while loading /storage/browser?project=ninthage-data-analytics
You are missing the following required permissions:

Project

storage.buckets.list

Check that the project ID is valid and you have permissions to access it. Learn more

Send feedback "

**Comment by duxbuse** [comment]
Ok I have now given you Storage Admin Role which is basically god tier permissions, aka you can delete the whole thing. So please dont do this :) But it should also let you rename files :P

**Comment by duxbuse** [comment]
OK seems that admin is the required power. I will investigate if there are some alternatives.
