### ISSUE TITLE
'VS' is reported as 'Invalid Army book'

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#49]
**Describe the bug**
When 'VS' is entered, i get the error log to say 'Invalid Army book'

**To Reproduce**
1. Add this list to the bot:

VANDERSANDE François
VS

440 - Magister, Wizard Master, Thaumaturgy, Second Awakening, 3 instances of Dark Shard 
430 - Magister, General, Wizard Master, Witchcraft, Binding Scroll, Obsidian Rock
355 - Tyrant, Shield, Heavy Armour, Hand Weapon (Secrets of the Doom Blade), Potion of Swiftness
265 - Sicarra Assassin, Throwing Weapons , Lethal Strike
250 - Chief, Shield, BSB (Banner of Discipline, Aether Icon), Light Armour, Binding Scroll
410 - 51 Rats - at - Arms, Spear, Standard (Banner of the Endless Swarm), Musician, Champion 410 - 51 Rats - at - Arms, Spear, Standard (Banner of the Endless Swarm), Musician, Champion 370 - 20 Vermin Guard, Standard Bearer (Lightning Rod), Musician, Champion
275 - 20 Plague Brotherhood, Standard Bearer (Banner of the Relentless Company), Musician, Champion
275 - 20 Plague Brotherhood, Standard Bearer (Banner of the Relentless Company), Musician, Champion 
120 - 5 Gutter Blades, Throwing Weapons 
120 - 5 Gutter Blades, Throwing Weapons 
140 - Meat Grinder
140 - Meat Grinder 
230 -  Lightning Cannon
135 - Weapon Team, Globe Launcher 
135 - Weapon Team, Globe Launcher 

**Expected behavior**
It should be recognized as Vermin Swarm book.

**Comments**
It is not purely missing 'VS' in your list it seems. As not for all entries I get this message with the same army name. E.g: 

Aleksander Jaworowski
VS
870 - Vermin Daemon, General
350 - Chief, Monstrous Rat, Shield, Heavy Armour (Ghostly Guard), Great Weapon
315 - Chief, Vermin Hulk Bodyguard, Battle Standard Bearer (Banner of the Endless Swarm), Light Armour, Great Weapon, Sceptre of Vermin Valour
255 - Magister, Wizard Adept, Witchcraft, Binding Scroll
445 - 58 Rats - at - Arms, Spear, Standard Bearer (Banner of the Endless Swarm), Musician, Champion
395 - 50 Rats - at - Arms, Spear, Standard Bearer (Banner of the Relentless Company), Musician, Champion
150 - 20 Giant Rats
135 - 10 Footpads, Musician
715 - 11 Vermin Hulks, Champion
200 - 8 Plague Disciples
120 - 5 Gutter Blades, Throwing Weapons
90 - Rat Swarms
230 - Lightning Cannon
230 - Lightning Cannon
4500

**Comment by duxbuse** [comment]
@marcqg This is an issue with the formatter.

It is translating `VS` to `The Vermin Swarm`  However new recruit format dictates it is simply `Vermin Swarm`. Is this an easy change on your end?
