### ISSUE TITLE
General not recognized

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#50]
**Describe the bug**
General not recognized, while it is in the list

**To Reproduce**
1. Add this list to bot:

James Smith
DE
755 - Beastmaster, Dragon, Paired Weapons (Lacerating Touch), Ring of the Obsidian Thrones, Obsidian Rock
430 - Temple Legate, Battle Standard Bearer (Aether Icon), Blades of Darag, Magical Heirloom, Ceinran's Gambit, War Smith 
335 - Legion Legate, General, Shield (Willow's Ward), Kraken's Hide, Basalt Infusion, Spear, Talisman of Shielding, Ring of the 9th Legion 
504 - 31 Dread Legionnaires, Standard Bearer (Executioner's Icon), Musician, Champion
400 - 25 Dread Legionnaires, Standard Bearer (Banner of the Relentless Company), Musician 8 Shadow Riders
235 - 28 Judicators, Champion, Musician, Standard Bearer (Academy Banner)
420 - 8 Warlock Acolytes, Champion
160 - 8 Harpies
365 - Kraken
265 - Mist Leviathan 

2) Error will see no general is selected.

**Expected behavior**
The Legion Legate should be recognized as general.

**Comment by duxbuse** [comment]
This seems to be an error with the new recruit validator. I have raised it with flammy so we shall see.

**Comment by duxbuse** [comment]
Ok just got word back from flammy. Issue is that legion legate is no longer a valid unit entry. He is now called Silexian officer, as a result the whole unit is ignored

**Comment by duxbuse** [comment]
He is working on getting old versions to be supported, but this will only work from once he can implement it and start recording changes as old versions.

So for this particular list it will never pass validation
