### ISSUE TITLE
TBL_INTERFACE_TABLEAU is out of sync

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#51]
**Describe the bug**
TBL_INTERFACE_TABLEAU is out of sync with tournament_lists.

**To Reproduce**
1. Go to Google BigQuerry
2. Click the three dots behind the table and choose Query
3. Make a query on it. For example: SELECT tournament FROM `ninthage-data-analytics.all_lists.TBL_INTERFACE_TABLEAU` group by tournament
4. Note that New Year's Revolution or Sanders Test List 4 is not in the list while these are available in tournament_lists.

**Expected behavior**
I expect all data from tournament_lists also be available TBL_INTERFACE_TABLEAU  as the query must collect everything.

**Additional context**
Possible issues: too long computing time on query = timeout? Schema changes on tournament_lists caused the query to stop working? ....

**Comment by duxbuse** [comment]
With the help of kd can we close this?

**Comment by SanderND** [comment]
Yes!

Verstuurd vanaf mijn iPhone
