### ISSUE TITLE
List is not read as list while the log says 'success'

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#53]
**Describe the bug**
A list is not recognized as a list, but the bot recognizes it as a 'success'.

**To Reproduce**
1. Upload this list to the bot:

Jacob Corteen
Infernal Dwarfs
550 - Prophet, General, Prophet of Lugar, Wizard Master, Alchemy, Pyromancy, Great Weapon, Breath of the Brass Bull, Essence of a Free Mind
305 - Vizier, Shield (Willow's Ward), Battle Standard Bearer (Legion Standard, Legion Standard), Blunderbuss, Alchemist's Alloy, Golden Idol of Shamut, Obsidian Rock
250 - Vassal Conjurer, Wizard Adept, Witchcraft, Binding Scroll
475 - 20 Citadel Guard, Flintlock Axe, Musician
460 - 20 Infernal Warriors, Shield, Blunderbuss, Standard Bearer (Banner of Speed), Musician, Champion
195 - 20 Vassal Levies, Paired Weapons, Bow, Musician
455 - 20 Disciples of Lugar, Paired Weapons, Musician
425 - 10 Taurukh Enforcers, Great Weapon, Blunderbuss, Musician
280 - 3 Taurukh Anointed, Paired Weapons
265 - Infernal Bastion
240 - Infernal Artillery, Titan Mortar
190 - 5 Vassal Cavalry
410 - Infernal Engine, Titan Mortar
4500

2: The error says: "t9a-data-test.docx
Success:
Additional Info
Lists read = 0
TK info Loaded = False
Possible TK name matches = []
Passed Validation = 0/0
Output Table = File was a test file so skipping upload"
​
**Expected behavior**
The list should be read as a list.

**Comment by duxbuse** [comment]
Source of this issue is that `Infernal Dwarfs` Is not a legal T9A army. They are `Infernal Dwarves`. But no matter I will alias `Infernal Dwarfs` to be treated as intended.
