### ISSUE TITLE
Players read from file too limited in log

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#54]
**Describe the bug**
The error log shows a list of players read from the file in case the file can be matched with TourneyKeeper.

**To Reproduce**
1. Upload 'Who_Let_the_Doge_Out.docx' (see attachment of this issue) to the bot.
2. In the error log it says:
Value Error
Number of lists read: 105 did not equal number of players on tourneykeeper: 111
Players read from file: ['Hugh Scarlin', 'Alistair Parren', 'Luke Tranter', 'Mark Greensill', 'Thomas Möller', 'Anthony Thompson', 'Christian Brauer', 'Maik Duus', 'Marius Maertens', 'Mal Patel', 'Max Warton', 'Ben Wadsworth', 'Hugo Chui', 'Dave Meachen', 'Marcel Ritsema', 'Yoeri van Alewijk', 'Niek Jacobs', 'Mike van der Meulen', 'Jelle van Alewijk', **'Alex Schmid', 'Scrub', 'Manfroni', 'Kirill Adelfinskiy', [...] alte Darling Dueholm',** 'Mehmet Camuroglu', 'Doug Lamb', 'adatopoulos', 'Emre Karakaş', 'Thomas Möller', 'Ir3k', 'Big Boss M.', 'Olli Katila', 'Erdem "Matrim"', 'McCrae Loudon', 'Anthony Thompson', 'Thomas Brazier', 'Jere Jukka', 'Jeremy Gottschalk', 'Michael Mattox', 'Mark Ciarlone', 'Ryan', 'Jørund ', 'Drew G', 'Antti Häkli', 'Marius Maertens', 'Christian Brauer', 'Germán San Martín ', 'Franklin Molina', 'Jose Enrique Toledo', 'Aarón “Aaercatl” Cava', 'Niklas Persson', 'Jeff Durham ', 'Mika'])

As you see the names are condensed by the [...] part. As a result it is a puzzle to find the missing names manually. 

**Expected behavior**
Option 1) A full list of names must be shown. Option 2) Alternatively, the text not recognized as name or army including reason why could be shown to make it even more easy to recognize the mistake.

**Attachments**
[Who Let the Doge Out.docx](https://github.com/duxbuse/ninthage-data-analytics/files/7750377/Who.Let.the.Doge.Out.docx)

**Comment by duxbuse** [comment]
This was closed with #56. We now only print out the names of people that were not connected properly
