### ISSUE TITLE
Upload error: 'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#55]
**Describe the bug**
An error without usable feedback after list uploading.

**To Reproduce**
1. Upload the attached list to the bot.
2. See error:

"Pandemic Picnic II.docx
Errors:
Value Error
'NoneType' object has no attribute 'append'"

**Expected behavior**
I wanted a successful upload or meaningful feedback on errors
[Pandemic Picnic II.docx](https://github.com/duxbuse/ninthage-data-analytics/files/7756570/Pandemic.Picnic.II.docx)
.

**Comment by duxbuse** [comment]
So fun fact this is because for this even they did not record secondary points. So after loading in the Tk data I just presumed that we would have secondary points but alas it is a `None`

**Comment by SanderND** [comment]
I uploaded the list Pandemic Picnic II.docx successfully now. Thank you for the fix.
