### ISSUE TITLE
Detailed logfiles shows TK names not in uploaded word file

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#57]
**Describe the bug**
While trying to debug the unsuccesfull reading of a document with lists, I came across strange names in the detailed error log on GCS. These names are mentioned as 'Read in from TK' but seem to have no relation with the file read and the players mentioned therein.

**To Reproduce**
1. Go to this log: https://console.cloud.google.com/logs/query;cursorTimestamp=2021-12-22T09:30:34.555Z;query=timestamp%3D%222021-12-22T09:30:34.555Z%22%0AinsertId%3D%22000000-7bc8b8a6-a397-4eb7-a190-2a8c9a0a1a88%22;timeRange=2021-12-22T06:47:20.727Z%2F2021-12-22T10:47:20.727196Z?project=ninthage-data-analytics

2. Read the players read in from TK such as 'Clement Konopnicki' or 'Felix Reisinger'.
3. Examine the file read in, see attachment, and see how none of the names lead to these names.

**Expected behavior**
I didnt expect the names of  'Clement Konopnicki' or 'Felix Reisinger' to be read.

**Additional context**
It might be I read this section of the log wrong. In that case, pleadse explain what is meant by Read from TK instead, to help me debugging the unsuccessfull list entry. The debugging has to with a different number of lists read in the file then registered in TK.

**Comment by duxbuse** [comment]
OK I presume that this is for `Aufs Team DACH die 1..docx`. 

`Clement Konopnicki` and `Felix Reisinger` are both registered on TK. So this probably means that the lists file forgot to add their lists.

I have modified the error list to be more helpful

```text
Lists read: 38
        Players registered on tourneykeeper: 42
        Players matched: 38
        Players in file but not TK: {'derplaetter-Tobias standard bearer', "Anton 'Stereotony' Hermann", 'Jan B', 'Phillipp', "Dominik 'teclis2000' W, (daemonik#9250)", 'Phillip', 'Mathieu'}
        Players in TK but not in file: {'Jan B.', 'Pacillo', 'Christian Mathieu', 'Dr. GonZo', 'Felix Reisinger', 'Clement Konopnicki', 'Dominik "teclis2000" W. (daemonik#9250)', 'derplaetter - Tobias S', 'Anton "Sterotony" Hermann', 'Philipp'}
```

However it did highlight an issue the players `phillip`  and `phillipp` are being tread as the same player. This may be skewing the game results
