### ISSUE TITLE
Error on name 'Romain'

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#61]
**Describe the bug**
While uploading a tourney one name, 'Romain' results in unmapped name. However, Romain is nor in the file, nor a name in TK. Why does the error say that "Value Error Players not uniquely mapped to tk: [('Romain', 44055), ('Romain', 44055)]"

**To Reproduce**
1. Go to https://discord.com/channels/910334907736272906/915385291429269505/923665860420313178.
2. Check yourself 'Romain' is not on TK for this tourney: https://tourneykeeper.net/Singles/TKLeaderboard.aspx?Id=3483
3. Check yourself 'Romain' is not in the file: https://console.cloud.google.com/storage/browser/_details/tournament-lists/%22Vermins%20ash%22%20The%209th%20Age%20Tournament.docx;tab=live_object?project=ninthage-data-analytics

**Expected behavior**
I didnt expect an error on 'Romain'.

**Comment by duxbuse** [comment]
@SanderND Can you please re check this one.

The discord link is for the tournament `Lëtz play T9A` Who does have a player named `romain`

The event `"Vermins ash" The 9th Age Tournament.docx`

Has a totaly different error
```text
Value Error
Lists read: 14
Players registered on tourneykeeper: 16
Players matched: 14
Players in file but not TK: {'Danylo', "Maxim'Inkvizitor Maximilian'Biba"}
Players in TK but not in file: {'Adeyev Dmitriy', 'Maxim"Inkvizitor Maximilian"Biba', 'Danylo ', 'Mark Abarenko'}
```

So a little confused as to what I need to do here. I will investigate why it has `Romain` twice though

**Comment by duxbuse** [comment]
And actually this is why its confused `Romain (Malakoff brothers )` and `romain (Grand Est 1)` both played this event. Since the team is on brackets its difficult for use to determine the player here cause we currently do ingest any team data

**Comment by SanderND** [comment]
So the capital letter is the only difference in the name isnt it?

**Comment by SanderND** [comment]
And indeed this is about Lets Play tournament... sorry for the sloppy issue creation

**Comment by duxbuse** [comment]
> 

yes that appears to be the issue

**Comment by SanderND** [comment]
When adding the Letz play list again. this error re-appeared. Attached the file.
[Letz play T9A.docx](https://github.com/duxbuse/ninthage-data-analytics/files/7802991/Letz.play.T9A.docx)

**Comment by SanderND** [comment]
This list is now read.
