### ISSUE TITLE
Double name in TK... or hidden names?

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#62]
**Describe the bug**
In Aufs Dach the player Philipp seems to exist twice, or not?

**To Reproduce**
1. Go to: https://tourneykeeper.net/Team/TKTeamLeaderboard.aspx?Id=3416
2. Click on 'Philipp' in team 4. You will see his names stays Philipp after clicking.
3. Scroll down to 'Philipp' in team 7. After clicking his name you will learn TK suddenly says he is 'Merlin'.

**Expected behavior**
I expect the playername to be unique and unambiguous. So there must be only one 'Philipp' otherwise matching goes wrong. Also i need to understand which name to use for linking: the name i see in the tourney or the name I see after clicking the player.

**Additional context**
I mistyped one 'Philipp' initially as 'Philip'. I repaired one in 'Merlin' but then 'Merlin' is not found. Now I change to 'Philipp' knowing I have two similar names in one file. This results in this log: https://discord.com/channels/910334907736272906/915385291429269505/923911871306813440

**Comment by duxbuse** [comment]
Ok So there is 3 Philips it seems for this event. `Philipp - VS`, `Philipp Förster -ASK`, `Phillipp - BH`

They do have different names though so let me see why they are colliding

**Comment by duxbuse** [comment]
OK there is an issue both players actually have the same name. They have differerent TK id's but I store them as a dict as so the same names just overwrite old values.

This also means I will need to also use the army they were playing to differentiate them. If 2 players with the same names play the same army however we have no way to separate them, unless they also load their army into TK but most people dont bother with that.

**Comment by SanderND** [comment]
I have seen players with a different army in TK then in the word file. So please ONLY add the name of army as differentiator and not as mandatory join field.

**Comment by duxbuse** [comment]
Ahh good call. Ok I have made the changes to ensure that we can support players with the same names.
However for some reason we dont get the codex information when retrieving player data from the api. So I have reached out to the TK guys to add that in.  So until that data comes in we will remain with no way to disambiguate players of the same name.
