### ISSUE TITLE
Registration of mapped name from document to TK

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#63]
**Is your feature request related to a problem? Please describe.**
The match between the playername in the document and the TK name is not registered in a table. As a result we cannot check if existing database entries were correctly mapped. Especially when the bot changes his routine due to updates we might want to trace down any incorrectly mapped players uploaded in the past to recognize where we need to remove old entries and load them again.

**Describe the solution you'd like**
Id like to register the mapping in  a table with the following fields: ingestion date, tourney, document playername, mapped TK playername. Optionally a field with the possible alternatives which were NOT taken into account.

**Possible alternatives**
Once a while drop all entries and read all files again. However, this feels like wasting good work and needs manual work. If deletion and uploading all files in the bucket to the bot again can be automated reliable, this is a valid alternative of course. However, i like precision tools (my proposed solution) better.

**Comment by duxbuse** [comment]
Ok so your thinking essentially a list of files that have not been successful that should be reattempted later on once updates have occurred ?

**Comment by SanderND** [comment]
No, i want all successful lists to be uploaded to be registered in such a way we know to which TK name they were matched. The TK player name is already in our database, but not the name that was read from the file. So actually my proposal is as small as creating a new field with the playername from the word document.

**Comment by duxbuse** [comment]
Do we have privacy concerns here though?

**Comment by duxbuse** [comment]
Closing as not planning to implement
