### ISSUE TITLE
Field with list in new recruit format

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#64]
**Is your feature request related to a problem? Please describe.**
Although we read in lists in New Recruit format, the users of the dashboard cannot browse list in that format.

**Describe the solution you'd like**
I'd like to present the option in the tab 'List display' to show the list in new recruit format.

**Comment by duxbuse** [comment]
Hmm so would you like the raw army list or after we have done some formatting?
