### ISSUE TITLE
Add unit stats to static data tables

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#69]
**Is your feature request related to a problem? Please describe.**
To start making a capabilities assessment of the armylists, id like to calculate with the stats of units.

**Describe the solution you'd like**
Id like to have a table with unit id, stats divided into single columns.

**Comment by duxbuse** [comment]
@marcqg Is this data avaliable?

**Comment by duxbuse** [comment]
This will also require automated retrieval as well as conversion to big query delimited format. then uploaded
