### ISSUE TITLE
Error code 501

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#72]
**Describe the bug**
After reading in the attached list I get an error 501 without any helpful error information.

**To Reproduce**
1) upload attached document to bot.
2) see error: "No I in UK UB Team Tournament.docx
Errors: Other Error
HTTP server responded with error code 501"

**Expected behavior**
I expect the lists to be read successfully or give me a meaningful error log so i can improve the document.

**Comment by SanderND** [comment]
This list has this error again: https://discord.com/channels/910334907736272906/915385291429269505/926080448323547166
[Who 8 My Wings.docx](https://github.com/duxbuse/ninthage-data-analytics/files/7792805/Who.8.My.Wings.docx)

**Comment by SanderND** [comment]
Also this list has the 501 error. Last thing i did before i get this error was replacing playername Michal Rusinek by Michał Rusinek. The difference in the strange 'l' in 'Michal'.

**Comment by duxbuse** [comment]
Ok so for the Who 8 my wings the issue stems from the player PY being in there twice.

```text
--PY—
Kingdom of Equitaine
475 - Duke, General, Barded Warhorse, Shield, Bastard Sword (Cleansing Light), Crusader's Salvation, Valour, Questng Oath and
Bastard Sword
440 - Damsel, Barded Warhorse, Wizard Master, Druidism, Binding Scroll
385 - Damsel, Barded Warhorse, Wizard Master, Divination
330 - Paladin, Barded Warhorse, Shield, Battle Standard Bearer (Aether Icon, Aether Icon), Lance (Wyrmwood Core), Basalt Infusion
170 - Paladin, Barded Warhorse, Halberd
724 - 13x Knights of the Realm, Standard Bearer (Banner of the Last Charge), Musician, Champion
436 - 9x Knights of the Realm, Standard Bearer (Aether Icon), Musician, Champion
725 - 14x Knights of the Quest, Standard Bearer (Flaming Standard), Musician, Champion
680 - 13x Knights of the Quest, Standard Bearer (Stalker's Standard), Musician, Champion
135 - 5x Yeoman Outriders, Shield, Bow
4500
```

```text
-- PY –
Kingdom of Equitaine
640 - Duke, Hippogriff, Shield (Dusk Forged), Bastard Sword (Cleansing Light), Basalt Infusion, Crown of Autocracy, Humility, Questing Oath and Bastard Sword
630 - Duke, Hippogriff, Shield, Crusader's Salvation, Hand Weapon (Tristan's Resolve), Potion of Swiftness, Dragonfire Gem, Humility, Grail Oath
370 - Damsel, General, Wizard Master, Shamanism, Crystal of the Valiant Charge
80 - Castellan, Heavy Armour, Bannerman (Legion Standard)
80 - Castellan, Heavy Armour, Bannerman (Legion Standard)
374 - 59 Peasant Levy, Standard Bearer, Musician, Champion
374 - 59 Peasant Levy, Standard Bearer, Musician, Champion
190 - 30 Peasant Levy, Standard Bearer, Champion
190 - 30 Peasant Levy, Standard Bearer, Champion
370 - 40 Peasant Crusaders, Shield, Standard Bearer (Oriflamme), Musician, Champion
165 - 20 Peasant Crusaders, Paired Weapons, Standard Bearer, Musician, Champion
165 - 20 Peasant Crusaders, Paired Weapons, Standard Bearer, Musician, Champion
223 - 14 Brigands
223 - 14 Brigands
165 - Sacred Reliquary
130 - Scorpion
130 - Scorpion
4499
```

Basically I never anticipated that a single player could be entered more than 1 list for the same event.

**Comment by SanderND** [comment]
You are right. One of the --PY-- had to be someone else.

Gaspard is player name of another list.

I fixed both, but now get "Who 8 My Wings.docx
Errors:
Value Error
TK giving bad data. Players registered:193 does not equal people who played:192"
