### ISSUE TITLE
Too many lists reported due to double mapping of players

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#74]
**Describe the bug**
Too many lists found and mapped to TK due to double mapping

**To Reproduce**
1) Upload Frome Fight Club Round One.docx
2) see log: "Frome Fight Club Round One.docx
Errors:
Value Error
Lists read: 38
Players registered on tourneykeeper: 36
Players matched: 38
Players in file but not TK: []
Players in TK but not in file: []"

**Expected behavior**
I expected every player to be mapped once. And if mapped multiple times, to learn at least which ones were double mapped to further investigate the root cause.

**Comment by duxbuse** [comment]
This is actually the same issue #77. I am now giving a more helpful error but there seems to be a problem with the data coming from TK. So this will require more investigation. Probably with the TK guys.

**Comment by duxbuse** [comment]
@SanderND This file has been successfully entered if I am not mistaken. If you agree please close this issue.
