### ISSUE TITLE
Dummy players on TK

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#80]
**Describe the bug**
Some tourneys have dummy names like player 1, player 2 etc

**To Reproduce**
1) New Years Revolution and Cossack Raid Master have names like player 1, 2, 3 etc that are not there in the file. The names seem to be kind of dummy names

**Expected behavior**
I only expect playername which also have a name.

https://tourneykeeper.net/Team/TKTeamLeaderboard.aspx?Id=3577 -> see last team.

**Comment by SanderND** [comment]
I tricked the bot with loading the players with a random list. Not sure what games are reported on them. Maybe use a dummy army for it which i filter out manually on Tableau.

**Comment by duxbuse** [comment]
Yeah so this is a fun one.

Looking here
https://www.tourneykeeper.net/Team/TKTeam.aspx?TeamId=4059&Id=3379

It seams that  for round 1 
![image](https://user-images.githubusercontent.com/6869131/147801891-e14ab2cf-b755-4d45-bb11-013f65f77fac.png)


This was the team. Then presumably they had to pull out and were replaced with
![image](https://user-images.githubusercontent.com/6869131/147801907-17e81e3f-607f-4eee-8244-d5f49b7d2f73.png)


So for this case we can either go to the TO and find out what lists they played. Or we can just assume that the new fill ins played with the lists from round 1. Though not sure if we can correctly pair which player maps to which army.


Second option is that I just ignore players called `player1-9` from having lists?
