### ISSUE TITLE
Not all units read from list

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#87]
[t9a-data-test.docx](https://github.com/duxbuse/ninthage-data-analytics/files/7799616/t9a-data-test.docx)

**Describe the bug**
Not all units are read from list.

**To Reproduce**
Upload the attached list and see error.

**Expected behavior**
All units are read.

**Comment by duxbuse** [comment]
@marcqg there is a bunch of nasty unicode characters hiding in this list. And the formatter basically drops most of the lines in the list.
![image](https://user-images.githubusercontent.com/6869131/148013666-61df59e2-a23b-490b-9ce2-6c0807266f67.png)

**Comment by marcqg** [comment]
I think there is a problem with the bot for this issue
For the army, when I look at what I receive
I found this :
Chay Davies-Smith
Warriors of the Dark Gods
650 - Chosen Lord, General, Karkadan, Shield (Dusk Forged), Hell Forged Armour, Hand Weapon (Burning Portent), Wrath, Dark Prelate
590 - Sorcerer, Dark Chariot, Wizard Master, Alchemy, Plate Armour (Basalt Infusion), Magical Heirloom, Talisman of the Void
455 - Feldrak Elder, Paired Weapons
455 - Feldrak Elder, Paired Weapons
449
the 6 lines with characters U+202C and U+202A are removed

**Comment by duxbuse** [comment]
Yeah so just retested this and the formatter is responding as expected. @SanderND What ever event this was from you should be able to re run now.

**Comment by SanderND** [comment]
I re-ran it, still same issue: https://discord.com/channels/910334907736272906/915385291429269505/933263283027312641

Re-opened the issues.

**Comment by duxbuse** [comment]
https://discord.com/channels/910334907736272906/915385291429269505/953818041899167764

This need in-depth investigation
