### ISSUE TITLE
Unregonized army format

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#94]
**Describe the bug**
The attached list has some armies  which are not properly read. See for example the list of 'Kombi'

```
Kombi 
Empire of Sonnstahl
1 Knight Commander @ 375 Pts General Cavalry Pick Plate Armour Shield Horse First Knight Titanic Might [50] Winter Cloak [70] Karadon's Courser [40] 1 Horse @ [0] Pts 
1 Inquisitor @ 85 Pts Paired Weapons Repeater Pistol (3+) Plate Armour Horse Silver Shots Hero's Heart [60] Basalt Infusion [35] 1 Horse @ [0] Pts 
1 Prelate @ 355 Pts Paired Weapons Plate Armour Horse King Slayer [50] Locket of Sunna [80] 1 Horse @ [0] Pts 
1 Wizard Master @ 350 Pts Wizard Master The Cosmology Magical Equipment allowance Hand Weapon 
1 Marshal - Battle Standard Bearer @ 175 Pts Hand Weapon Plate Armour Shield Battle Standard Willow's Ward [15] 
11 Knightly Orders @ 523 Pts Knightly Orders Lance Plate Armour Shield Standard Musician Horse Stalker's Standard [40] 1 Champion @ [10] Pts 12 Horse @ [0] Pts 
17 Light Infantry - Crossbowmen @ 253 Pts Crossbow (4+) Musician 
20 Heavy Infantry - Halberdiers @ 185 Pts Halberds Halberd Light Armour Shield Standard Musician Support Unit 
20 Heavy Infantry - Halberdiers @ 185 Pts Halberds Halberd Light Armour Shield Standard Musician Support Unit 
24 Imperial Guard @ 450 Pts Great Weapon Plate Armour Standard Musician 1 Champion @ [10] Pts 
5 Reiters @ 180 Pts Brace of Pistols (4+) Light Armour Horse Fire on Impact! 5 Horse @ [0] Pts 
5 Reiters @ 180 Pts Brace of Pistols (4+) Light Armour Horse Fire on Impact! 5 Horse @ [0] Pts 
1 Steam Tank @ 475 Pts Steel Ram Steam Cannon (3+) Steam Powered 1 Steel Ram @ [0] Pts 
1 Imperial Artillery - Cannon (4+) @ 245 Pts Cannon (4+) 
1 Imperial Artillery - Volley Gun (4+) @ 180 Pts Volley Gun (4+)
Total Army Cost: 4496 
```

Here is another format I have also just seen:
```
Vermin Swarm
1335/1800
Core Units: 1284/1125
Special: 665
Tunnel Gunners: 585/1350
Bread and Games: 630/900
Total: 4499
250 - Vermin Senator, GG, Senatorial Litter, Rod of Battle, Obsidian Rock
305 - Bloodfur Legate, Secrets of the Doom Blade, Shield, Potion of Swiftness.
295 - Swarm Priest, Adept Witchcraft, Holy Triumvirate, Caelysian Pantheon, Book of Arcane Mastery.
265 - Swarm Priest, Adept Witchcraft, Holy Triumvirate, Caelysian Pantheon, Tome of the Ratking.
220 - Swarm Priest, Adept Thaumaturgy, Holy Triumvirate, Caelysian Pantheon.
556 - 46 Blackfur Veterans, EMC & Eagle Standard, Rending Banner.
503 - 54 Vermin Legionaries, Spear & Shield, EMC & Eagle Standard, Rending Banner.
225 - 25 Vermin Legionaries, Shield, EM & Eagle
Standard, Aether Icon.
525 - 6 Murmillo Brutes, Halberd & Shield, EM & Eagle Standard.
140 - 10 Shadowfur Stalkers, Throwing Weapons.
185 - 3 Weapon Teams, Deepfire Thrower.
200 - Doomspark Device.
200 - Doomspark Device.
315 - Arena Beast, Underworld Beast.
315 - Arena Beast, Underworld Beast.
```

**Comment by marcqg** [comment]
The Kombi list will be : 
Kombi
Empire of Sonnstahl
375 - Knight Commander, General Cavalry Pick Plate Armour Shield Horse First Knight Titanic Might, Winter Cloak, Karadon's Courser, 1 Horse
85 - Inquisitor, Paired Weapons Repeater Pistol Plate Armour Horse Silver Shots Hero's Heart, Basalt Infusion, 1 Horse
355 - Prelate, Paired Weapons Plate Armour Horse King Slayer, Locket of Sunna, 1 Horse
350 - Wizard Master, Wizard Master The Cosmology Magical Equipment allowance Hand Weapon
175 - Marshal-Battle Standard Bearer, Hand Weapon Plate Armour Shield Battle Standard Willow's Ward
523 - 11x Knightly Orders, Knightly Orders Lance Plate Armour Shield Standard Musician Horse Stalker's Standard, 1 Champion, 12 Horse
253 - 17x Light Infantry-Crossbowmen, Crossbow Musician
185 - 20x Heavy Infantry-Halberdiers, Halberds Halberd Light Armour Shield Standard Musician Support Unit
185 - 20x Heavy Infantry-Halberdiers, Halberds Halberd Light Armour Shield Standard Musician Support Unit
450 - 24x Imperial Guard, Great Weapon Plate Armour Standard Musician 1 Champion
180 - Reiters, Brace of Pistols Light Armour Horse Fire on Impact! 5 Horse
180 - Reiters, Brace of Pistols Light Armour Horse Fire on Impact! 5 Horse
475 - Steam Tank, Steel Ram Steam Cannon Steam Powered 1 Steel Ram
245 - Imperial Artillery-Cannon, Cannon
180 - Imperial Artillery-Volley Gun, Volley Gun
4496

**Comment by marcqg** [comment]
the VS will be : 
Vermin Swarm
250 - Vermin Senator, GG, Senatorial Litter, Rod of Battle, Obsidian Rock
305 - Bloodfur Legate, Secrets of the Doom Blade, Shield, Potion of Swiftness,
295 - Swarm Priest, Adept Witchcraft, Holy Triumvirate, Caelysian Pantheon, Book of Arcane Mastery,
265 - Swarm Priest, Adept Witchcraft, Holy Triumvirate, Caelysian Pantheon, Tome of the Ratking,
220 - Swarm Priest, Adept Thaumaturgy, Holy Triumvirate, Caelysian Pantheon,
556 - 46x Blackfur Veterans, EMC & Eagle Standard, Rending Banner,
503 - 54x Vermin Legionaries, Spear & Shield, EMC & Eagle Standard, Rending Banner,
225 - 25x Vermin Legionaries, Shield, EM & Eagle Standard, Aether Icon,
525 - 6x Murmillo Brutes, Halberd & Shield, EM & Eagle Standard,
140 - 10x Shadowfur Stalkers, Throwing Weapons,
185 - 3x Weapon Teams, Deepfire Thrower,
200 - Doomspark Device,
200 - Doomspark Device,
315 - Arena Beast, Underworld Beast,
315 - Arena Beast, Underworld Beast,
4499

**Comment by marcqg** [comment]
You can try them again :)

**Comment by duxbuse** [comment]
seems functional to me now
