### ISSUE TITLE
Formatter stripping out player name

### ISSUE THREAD

**Issue by duxbuse** [duxbuse/ninthage-data-analytics#97]
@marcq
When sending this an input

```text
6149c7afb34c97c496886096
Dread Elves
Ikit976 - Dread Elves
435 - Warlock Outcast Wizard Master, Witchcraft, Binding Scroll
400 - Temple Exarch Alchemy, General, War Smith, Blades of Darag, Mask of the War Crow, Ceinran’s Scale
330 - Silexian Officer Battle Standard Bearer (Flaming Standard), Spear, Shield (Willow's Ward), Kraken's Hide, Seal of the 9th Fleet, Potion of Strength
565 - 30 Temple Militants, Champion, Musician, Standard Bearer (Rending Banner)
200 - 10 Raiding Parties, Corsair and Repeater Handbow, champion
375 – 20 Silexian Auxiliaries Champion, Musician, Standard Bearer (Rending Banner)
628 - 24 Obsidian Guards, Champion, Musician, Standard Bearer (Caedhren's Pennon)
502 - 21 Obsidian Guards, Champion, Musician, Standard Bearer (Aether Icon)
170 – 5 Harpies
310 – Altar, Crucible of Slaughter
155 – Gorgon, Paired Weapons
170 – 5 Black Cloacks
260 – Mist Leviathan
Total- 4500
```

I am receiving the following output:
```text
435 - Warlock Outcast Wizard Master, Witchcraft, Binding Scroll
400 - Temple Exarch Alchemy, General, War Smith, Blades of Darag, Mask of the War Crow, Ceinran's Scale
330 - Silexian Officer Battle Standard Bearer (Flaming Standard), Spear, Shield (Willow's Ward), Kraken's Hide, Seal of the 9th Fleet, Potion of Strength
565 - 30x Temple Militants, Champion, Musician, Standard Bearer (Rending Banner)
200 - 10x Raiding Parties, Corsair and Repeater Handbow, champion
375 - 20x Silexian Auxiliaries Champion, Musician, Standard Bearer (Rending Banner)
628 - 24x Obsidian Guards, Champion, Musician, Standard Bearer (Caedhren's Pennon)
502 - 21x Obsidian Guards, Champion, Musician, Standard Bearer (Aether Icon)
170 - 5x Harpies
310 - Altar, Crucible of Slaughter
155 - Gorgon, Paired Weapons
170 - 5x Black Cloacks
260 - Mist Leviathan
4500 - Total
```

You can see that the player name `6149c7afb34c97c496886096` and the army name `Dread Elves` are being lost.

Note that the top two lines of the input are separate fields in Fading flame data. The remainder is the raw army list as stored by fading flame. This is partly confusing because his name is in the army list field as is the army. This is not the case for many army lists.

**Comment by marcqg** [comment]
Will be converted in : 
Ikit976
Dread Elves
435 - Warlock Outcast Wizard Master, Witchcraft, Binding Scroll
400 - Temple Exarch Alchemy, General, War Smith, Blades of Darag, Mask of the War Crow, Ceinran's Scale
330 - Silexian Officer Battle Standard Bearer (Flaming Standard), Spear, Shield (Willow's Ward), Kraken's Hide, Seal of the 9th Fleet, Potion of Strength
565 - 30x Temple Militants, Champion, Musician, Standard Bearer (Rending Banner)
200 - 10x Raiding Parties, Corsair and Repeater Handbow, champion
375 - 20x Silexian Auxiliaries Champion, Musician, Standard Bearer (Rending Banner)
628 - 24x Obsidian Guards, Champion, Musician, Standard Bearer (Caedhren's Pennon)
502 - 21x Obsidian Guards, Champion, Musician, Standard Bearer (Aether Icon)
170 - 5x Harpies
310 - Altar, Crucible of Slaughter
155 - Gorgon, Paired Weapons
170 - 5x Black Cloacks
260 - Mist Leviathan
4500

**Comment by marcqg** [comment]
@SanderND you can try again :)

**Comment by SanderND** [comment]
This one is not from me. @duxbuse: this one is for you.

**Comment by duxbuse** [comment]
I recon this is all good now
