### ISSUE TITLE
Static data of magic items

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#99]
**Is your feature request related to a problem? Please describe.**
The values in field unit_upgrade cant be recognized as magic item. Id like to match them with the static magic item data to identify the magic items.

**Describe the solution you'd like**
Id like to have a table with all magic items from all books including version and category (e.g. magic weapon) so i can join that data in tableau and make matches. 

**Describe alternatives you've considered**
We might do this one step earlier in the process and already categorize the units in the backend.

**Comment by marcqg** [comment]
this will be available here : /{locale}/api/v1/data_analytics/ninth_ages/special_items
as : 
{
            "id": 1272,
            "name": "Rune of Mastery",
            "version_id": 5,
            "army_id": 79,
            "latex_key": "runeofmastery"
        }

**Comment by duxbuse** [comment]
Ok all done locked and loaded
